### ISSUE TITLE
Is the 30 minutes window to search for new plugins still up to date ?

### ISSUE THREAD

**Issue by sorasful** [traefik/plugindemo#19]
Hi there,

I forked a repository of a plugin to add an additional behavior, it's been almost 2 hours and it still doesn't show in the catalog. I was wondering if the time window of 30 minutes has changed maybe ?

I made sure : 
- to have git tags
- to add topics to my github project (I've added more just in case)
- I've created new release for my tags just in case

Here's my project : 
https://github.com/sorasful/jwt-middleware-optional  

I don't see any issues either on the repository. 

Do you have some pointers ? Or maybe I just need to wait a bit more ? 

Thanks for your time !

**Comment by ldez** [comment]
Hello,

the forks are not handled as valid plugins, because forks are mainly related to PRs.

So you have to create a "hard fork" (copy the repo).
