### ISSUE TITLE
Question about the plugings in general

### ISSUE THREAD

**Issue by overthetop** [traefik/plugindemo#7]
I'm not so familiar with traefik. Can I create a custom plugin and use it in the traefik community edition without Pilot? If not what would be the way for me? Should I create a custom middleware and compile the source code of the proxy myself?

**Comment by darkweaver87** [comment]
Hello,

No, plugins need your traefik to be associated to a token in Pilot but Pilot is totally free.

Rémi

**Comment by overthetop** [comment]
Thx @darkweaver87 Does that mean that I can install traefik and pilot locally on an isolated environment?

**Comment by darkweaver87** [comment]
No, you can install traefik locally but Pilot is an online service.

**Comment by overthetop** [comment]
I see. So basically I can't create proprietary plugins because Pilot needs to access them somehow. In my case the solution would be to write my own custom middleware right?

**Comment by darkweaver87** [comment]
When it starts traefik will download the plugins you declared. 
You can use your own plugin in a development context but only for 30 minutes (then traefik will disable it until a restart).
If you want to use it in a production environment you will need to publish it. It's win-win :-)
There is no private registry for now.
If you don't want to share it with the community then yes you'll have to build your own version of traefik with a middleware.
